feat: saving button animation
CodeGov-org/codegov-website pull request #44
Opened 2024-02-15 20:02 UTC by MiaArnix

2024-02-15 20:03 UTC, MiaArnix commented on lib/tailwind/common.css
added button height to prevent stretching in case icon is added

2024-02-15 20:42 UTC, nathanosdev commented on src/frontend/src/app/core/layout/secondary-navbar/secondary-navbar.component.ts
> +            [appTooltip]="isTouchScreen() ? null : 'Log in'"
Is it needed when the tooltip directive is already checking this?

2024-02-15 20:42 UTC, nathanosdev commented on src/frontend/src/app/pages/profile-edit/reviewer-personal-info-form/reviewer-personal-info-form.component.ts
> +      this.submitButton?.nativeElement.dispatchEvent(new Event('mouseleave'));
Use `ngOnDestroy` in the tooltip directive instead.

2024-02-15 20:42 UTC, nathanosdev commented on src/frontend/src/app/pages/profile-edit/reviewer-social-media-form/reviewer-social-media-form.component.ts
> +          [appTooltip]="isSaving ? 'Saving...' : null"
No need for a `Saving...' tooltip, but add an aria label to the icon.

2024-02-15 20:42 UTC, nathanosdev commented on lib/tailwind/common.css
I would prefer to use `position: relative` on the button and `position: absolute` on the icon so it's not affected by the button's padding

2024-02-15 22:22 UTC, nathanosdev approved these changes

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/core/ui/tooltip/tooltip.directive.ts
>      this.overlayRef.detach();
Make a separate, private function called `hide()`.

Call this event handler `onMouseLeave()`.

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/core/ui/tooltip/tooltip.directive.ts
> +  public showOnMobileScreen(): void {
Call this `onClick()`, call the `mouseenter` event above `onMouseEnter()`.

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/core/ui/tooltip/tooltip.directive.ts
> +      window.matchMedia('(pointer: coarse)').matches
Make an `isTouchScreen()` function

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/core/ui/tooltip/tooltip.directive.ts
> +      const tooltipPortal = new ComponentPortal(TooltipComponent);
Extract this part into a separate function to reuse with `onMouseLeave()`

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/core/ui/tooltip/tooltip.directive.ts
>    @HostListener('mouseleave')
Renamed to `onMouseLeave()`

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/pages/profile-edit/admin-personal-info-form/admin-personal-info-form.component.ts
>            [ngClass]="isSaving ? 'text-transparent' : ''"
Use `aria-hidden` so that this text is not visible to screen readers. Move this and `text-transparent` onto an element wrapping the `Save` text

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/pages/profile-edit/admin-personal-info-form/admin-personal-info-form.component.ts
> +          [attr.aria-label]="isSaving ? 'Saving' : 'Save'"
Move aira-label to the icon, use only `Saving`

2024-02-15 22:22 UTC, nathanosdev commented on src/frontend/src/app/pages/profile-edit/reviewer-personal-info-form/reviewer-personal-info-form.component.ts
> +            Fix the validation errors
_"Uh-oh! There are some errors in your form. Please fix them and try again."_ or similar ;)

2024-02-15 22:23 UTC, nathanosdev requested changes
See comments

2024-02-16 09:59 UTC, nathanosdev commented on src/frontend/src/app/pages/profile-edit/admin-personal-info-form/admin-personal-info-form.component.ts
> +          <div [ngClass]="isSaving ? 'aria-hidden text-transparent' : ''">
`aria-hidden` should be an attribute

2024-02-16 11:34 UTC, nathanosdev approved these changes

2024-02-16 11:41 UTC, merged