feat: accessibility improvements and cleanup
CodeGov-org/codegov-website pull request #51
Opened 2024-02-18 16:09 UTC by nathanosdev

Marketing and proposal sites
- improved accessibility of dropdown
- added dropdown chevron animation

Proposal site
- remove proposalTypes
- id's are kebab case
- cache profile data
- reusable form validation info
- wallet address link
- wallet address input hint
- neuron id link
- reusable loading button
- fixed button focus box shadows
- accessibility improvements
  - form controls
  - key value info
  - tooltips

2024-02-18 19:05 UTC, MiaArnix requested changes

2024-02-18 19:05 UTC, MiaArnix commented on src/frontend/src/app/core/ui/loading-button/loading-button.component.ts
> +    <button type="submit" [disabled]="disabled" [class]="btnClass">
type is not using the input

2024-02-18 19:05 UTC, MiaArnix commented on src/frontend/src/app/core/ui/loading-button/loading-button.component.ts
> +        Save
use content projection

2024-02-18 19:42 UTC, nathanosdev commented on src/frontend/src/app/core/ui/form-validation-info/form-validation-info.component.ts
> +      :host-context(.form-validation-info__hidden) {
Use modifier syntax instead of child syntax

2024-02-19 22:09 UTC, MiaArnix approved these changes

2024-02-19 22:11 UTC, merged